name: Update Daily Wireless Tip Gist

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 UTC (~3:30 PM IST)
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update Gist with today's tip
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import datetime
          import os

          # Get today's date in yyyy-mm-dd format
          today = datetime.datetime.utcnow().date().isoformat()

          # Read tips file
          with open("wireless_tips_1_year.txt", "r") as file:
              tips = file.readlines()

          # Find today's tip
          today_tip = next((line for line in tips if line.startswith(today)), None)

          if not today_tip:
              raise Exception("No tip found for today!")

          # Prepare the payload
          import requests
          update_url = f"https://api.github.com/gists/{os.environ['GIST_ID']}"
          headers = {"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"}
          payload = {
              "files": {
                  "gistfile1.txt": {
                      "content": today_tip.strip()
                  }
              }
          }

          response = requests.patch(update_url, json=payload, headers=headers)
          if response.status_code != 200:
              raise Exception(f"Failed to update gist: {response.content}")
