name: Update Daily Wireless Tip Gist

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 UTC (~3:30 PM IST)
  workflow_dispatch:       # Allows you to run it manually too

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_TOKEN: ${{ secrets.token }}
        run: python update_gist.py
