name: Update Wi-Fi News Digest

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Digest Generator
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          TOKEN: ${{ secrets.token }}
        run: python update_wifi_news_digest.py
